---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian-sync-share
  labels:
    app: obsidian-sync-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian-sync-share
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obsidian-sync-share
    spec:
      containers:
      - name: obsidian-sync-share
        imagePullPolicy: "IfNotPresent"
        image: alterzz/obsidian-sync-share-server:latest
        ports:
        - name: http
          containerPort: 8789
          protocol: TCP
        env:
        - name: "JAVA_OPTS"
          value: "-Xmx512m"
        volumeMounts:
          - name: k8s-pv02
            mountPath: /app/user_store
            subPath: obsidian-sync/user_store
      volumes:
      - name: k8s-pv02
        persistentVolumeClaim:
          claimName: synology-k8s-pv02
