---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-sync
spec:
  type: NodePort
  selector:
    app: obsidian-sync
  ports:
  - name: "tcp-port" 
    port: 8789 
    targetPort: 8080
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
    - 192.168.0.223
    - 192.168.0.224
